/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from './calendar.module';
import * as i2 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as i3 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as i4 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as i5 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as i6 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as i7 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as i8 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as i9 from '../node_modules/ionic-angular/components/select/select-popover-component.ngfactory';
import * as i10 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as i11 from './calendar.ngfactory';
import * as i12 from '@angular/common';
import * as i13 from '@angular/forms';
import * as i14 from 'ionic-angular/module';
export const NgCalendarModuleNgFactory:i0.NgModuleFactory<i1.NgCalendarModule> = i0.ɵcmf(i1.NgCalendarModule,
    ([] as any[]),(_l:any) => {
      return i0.ɵmod([i0.ɵmpd(512,i0.ComponentFactoryResolver,i0.ɵCodegenComponentFactoryResolver,
          [[8,[i2.ActionSheetCmpNgFactory,i3.AlertCmpNgFactory,i4.IonicAppNgFactory,
              i5.LoadingCmpNgFactory,i6.ModalCmpNgFactory,i7.PickerCmpNgFactory,i8.PopoverCmpNgFactory,
              i9.SelectPopoverNgFactory,i10.ToastCmpNgFactory,i11.CalendarComponentNgFactory]],
              [3,i0.ComponentFactoryResolver],i0.NgModuleRef]),i0.ɵmpd(4608,i12.NgLocalization,
          i12.NgLocaleLocalization,[i0.LOCALE_ID]),i0.ɵmpd(4608,i13.ɵi,i13.ɵi,([] as any[])),
          i0.ɵmpd(4608,i13.FormBuilder,i13.FormBuilder,([] as any[])),i0.ɵmpd(512,
              i12.CommonModule,i12.CommonModule,([] as any[])),i0.ɵmpd(512,i13.ɵba,
              i13.ɵba,([] as any[])),i0.ɵmpd(512,i13.FormsModule,i13.FormsModule,([] as any[])),
          i0.ɵmpd(512,i13.ReactiveFormsModule,i13.ReactiveFormsModule,([] as any[])),
          i0.ɵmpd(512,i14.IonicModule,i14.IonicModule,([] as any[])),i0.ɵmpd(512,i1.NgCalendarModule,
              i1.NgCalendarModule,([] as any[]))]);
    });
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2Viby9XRElSL0lvbmljMi1DYWxlbmRhci9zcmMvY2FsZW5kYXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvY2Viby9XRElSL0lvbmljMi1DYWxlbmRhci9zcmMvY2FsZW5kYXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
