/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from '@angular/core';
import * as i1 from '../node_modules/ionic-angular/components/scroll/scroll.ngfactory';
import * as i2 from 'ionic-angular/components/scroll/scroll';
import * as i3 from './init-position-scroll';
const styles_initPositionScrollComponent:any[] = ([] as any[]);
export const RenderType_initPositionScrollComponent:i0.RendererType2 = i0.ɵcrt({encapsulation:2,
    styles:styles_initPositionScrollComponent,data:{}});
export function View_initPositionScrollComponent_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[i0.ɵqud(402653184,1,{_scrollContent:0}),(_l()(),i0.ɵted((null as any),
      ['\n        '])),(_l()(),i0.ɵeld(0,(null as any),(null as any),4,'ion-scroll',
      [['scrollY','true'],['style','height:100%'],['zoom','false']],[[2,'scroll-x',
          (null as any)],[2,'scroll-y',(null as any)]],(null as any),(null as any),
      i1.View_Scroll_0,i1.RenderType_Scroll)),i0.ɵdid(49152,(null as any),0,i2.Scroll,
      ([] as any[]),{scrollY:[0,'scrollY'],zoom:[1,'zoom']},(null as any)),(_l()(),
      i0.ɵted(0,['\n            '])),i0.ɵncd(0,0),(_l()(),i0.ɵted(0,['\n        '])),
      (_l()(),i0.ɵted((null as any),['\n    ']))],(_ck,_v) => {
    const currVal_2:any = 'true';
    const currVal_3:any = 'false';
    _ck(_v,3,0,currVal_2,currVal_3);
  },(_ck,_v) => {
    const currVal_0:any = i0.ɵnov(_v,3).scrollX;
    const currVal_1:any = i0.ɵnov(_v,3).scrollY;
    _ck(_v,2,0,currVal_0,currVal_1);
  });
}
export function View_initPositionScrollComponent_Host_0(_l:any):i0.ɵViewDefinition {
  return i0.ɵvid(0,[(_l()(),i0.ɵeld(0,(null as any),(null as any),1,'init-position-scroll',
      ([] as any[]),(null as any),(null as any),(null as any),View_initPositionScrollComponent_0,
      RenderType_initPositionScrollComponent)),i0.ɵdid(4898816,(null as any),0,i3.initPositionScrollComponent,
      [i0.ElementRef],(null as any),(null as any))],(null as any),(null as any));
}
export const initPositionScrollComponentNgFactory:i0.ComponentFactory<i3.initPositionScrollComponent> = i0.ɵccf('init-position-scroll',
    i3.initPositionScrollComponent,View_initPositionScrollComponent_Host_0,{scrollX:'scrollX',
        scrollY:'scrollY',zoom:'zoom',maxZoom:'maxZoom',initPosition:'initPosition',
        emitEvent:'emitEvent'},{onScroll:'onScroll'},['*']);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvY2Viby9XRElSL0lvbmljMi1DYWxlbmRhci9zcmMvaW5pdC1wb3NpdGlvbi1zY3JvbGwubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vaG9tZS9jZWJvL1dESVIvSW9uaWMyLUNhbGVuZGFyL3NyYy9pbml0LXBvc2l0aW9uLXNjcm9sbC50cyIsIm5nOi8vL2hvbWUvY2Viby9XRElSL0lvbmljMi1DYWxlbmRhci9zcmMvaW5pdC1wb3NpdGlvbi1zY3JvbGwudHMuaW5pdFBvc2l0aW9uU2Nyb2xsQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9ob21lL2NlYm8vV0RJUi9Jb25pYzItQ2FsZW5kYXIvc3JjL2luaXQtcG9zaXRpb24tc2Nyb2xsLnRzLmluaXRQb3NpdGlvblNjcm9sbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgICAgICA8aW9uLXNjcm9sbCBzY3JvbGxZPVwidHJ1ZVwiIHpvb209XCJmYWxzZVwiIHN0eWxlPVwiaGVpZ2h0OjEwMCVcIj5cbiAgICAgICAgICAgIDxuZy1jb250ZW50PjwvbmctY29udGVudD5cbiAgICAgICAgPC9pb24tc2Nyb2xsPlxuICAgICIsIjxpbml0LXBvc2l0aW9uLXNjcm9sbD48L2luaXQtcG9zaXRpb24tc2Nyb2xsPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7NERDQUE7TUFBQSxpQkFDUTtNQUFBO1VBQUE7MkNBQUEsVUFBQTtNQUFBLHFFQUE0RDthQUFBLCtCQUN4RCxNQUF5QjtNQUNoQjtJQUZEO0lBQWU7SUFBM0IsV0FBWSxVQUFlLFNBQTNCOztJQUFBO0lBQUE7SUFBQSxXQUFBLG1CQUFBOzs7O29CQ0RSO01BQUE7NENBQUEsVUFBQTtNQUFBOzs7OzsifQ==
